### ISSUE TITLE
Roadmap 2

### ISSUE THREAD

**Issue by xiaohuoni** [xiaohuoni/umi-antd-pro#10]
### Big Features

* [x] **物料市场**，将pro的页面拆分成物料，umijs/umi#1350，ant-design/ant-design-pro#2250 https://github.com/umijs/umi-blocks
* [ ] **主题配置**，类似 `pro` 的设置页面 ，使用umi-plugin的技术实现，添加插件。
* [x] 支持**动态菜单**，通过 `http`请求，获取到服务端的菜单  https://github.com/ant-design/ant-design-pro/pull/2928
* [x] **动态的权限配置**，由服务端下发权限，本地使用mock数据实现。将现有的菜单和权限做一个分离。https://github.com/ant-design/ant-design-pro/pull/2911

**Comment by xiaohuoni** [comment]
wz：理想状态 可以使用脚手架构建不同类型的项目 比如是否需要权限路由 然后组件 可以从物料市场拿来直接使用 这样就很舒服了

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/2739
路由配置可以根据不同的权限redirect到不同地址吗？

**Comment by xiaohuoni** [comment]
拆分之后要怎样跟上官方的更新？

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/2809

**Comment by xiaohuoni** [comment]
Ant Design Pro 如何动态修改路由配置文件config/router.config.js
https://github.com/ant-design/ant-design-pro/issues/2839

**Comment by xiaohuoni** [comment]
兼容ie10

**Comment by xiaohuoni** [comment]
> 拆分之后要怎样跟上官方的更新？

使用pro的项目构建，通过npm安装ant-design-pro的形式使用？

**Comment by xiaohuoni** [comment]
> 主题配置，类似 pro 的设置页面 ，使用umi-plugin的技术实现，添加插件。

存在bug，less失效问题，考虑能不能直接通过umi的设置来实现这个功能，参考umi-ui？

**Comment by xiaohuoni** [comment]
> 兼容ie10

ie10还支持flex，应该不会有太多问题，后续用windows跑一下看看，在做评估

**Comment by xiaohuoni** [comment]
@ctq123 现在我选这一套antd design pro 也是非常痛苦，看demo感觉好强大高大上，但其实开发流程反而复杂了，前端代码比后端还重，正如楼主所说，其实我们要的就是既快简单，又能直接上手的脚手架，有些东西封装得太好，要修改起来反而很痛苦  
我觉得这一套封装得太好了，正是太好了反而不好，耦合度不要太高了。我们是不是应该从用户的角度考虑，将初始的小盒子交给用户，各种功能拆分开来，将选择权真正交给用户，让用户选择。

**Comment by id77** [comment]
你文件夹Form，路由里面component 却用Forms

**Comment by id77** [comment]
不知道如何加路由参？

**Comment by xiaohuoni** [comment]
这只是一个测试的demo，只做为一些新用法的测试，你可以直接看pro项目，会好一点

**Comment by id77** [comment]
> 这只是一个测试的demo，只做为一些新用法的测试，你可以直接看pro项目，会好一点

我现在有个需求，要接受后端返回的路由，进行展示。尝试使用你这个方法，但是路径有错误，不得其解。
新增的page的路径总是被转为小写。原有的page却能正常访问。

**Comment by xiaohuoni** [comment]
这需要看你使用配置式路由，还是约定式路由了
